In [2]:
import pandas as pd
import time
from tqdm import tqdm
tqdm.pandas()
time_start=time.time()

In [3]:
train=pd.read_csv('invite_info.txt',sep='\s+',names=['qid','uid','time','target'])
test2=pd.read_csv('invite_info_evaluate_2_0926.txt',sep='\s+',names=['qid','uid','time'])
test=pd.read_csv('invite_info_evaluate_1.txt',sep='\s+',names=['qid','uid','time'])

In [4]:
#计算问题时间 和问题时间减去邀请时间

In [5]:
train['invite_day']=train['time'].progress_apply(lambda x:x[1:].split('-H')[0])
test['invite_day']=test['time'].progress_apply(lambda x:x[1:].split('-H')[0])

100%|██████████| 9489162/9489162 [00:17<00:00, 541808.18it/s]
100%|██████████| 1141683/1141683 [00:02<00:00, 523306.81it/s]

In [6]:
test2['invite_day']=test2['time'].progress_apply(lambda x:x[1:].split('-H')[0])

100%|██████████| 1141718/1141718 [00:02<00:00, 522097.35it/s]

In [7]:
all_data=pd.concat([train[['qid','uid','time','invite_day']],test2,test])

In [8]:
feature_q=all_data.groupby(['qid','invite_day']).agg({'uid':'count'})

In [9]:
feature_q=feature_q.reset_index()
feature_q.columns=['qid','invite_day','q_yesterday_invite']

In [10]:
feature_u=all_data.groupby(['uid','invite_day']).agg({'qid':'count'}).reset_index()
feature_u.columns=['uid','invite_day','u_yesterday_invite']

In [11]:
feature_u.head()

           uid invite_day  u_yesterday_invite
0  M1000000382       3842                   1
1  M1000000382       3844                   1
2  M1000000382       3846                   1
3  M1000000382       3860                   1
4  M1000000382       3861                   1

In [12]:
feature_u['invite_day']=feature_u['invite_day'].astype(int)+1
feature_q['invite_day']=feature_q['invite_day'].astype(int)+1

In [13]:
feature_u['invite_day']=feature_u['invite_day'].astype(str)
feature_q['invite_day']=feature_q['invite_day'].astype(str)
all_data['invite_day']=all_data['invite_day'].astype(str)

In [14]:
all_data=pd.merge(all_data,feature_u,how='left',on=['uid','invite_day'])
all_data=pd.merge(all_data,feature_q,how='left',on=['qid','invite_day'])

In [15]:
all_data=all_data.drop_duplicates(['qid','uid'])

In [16]:
all_data=all_data.reset_index(drop=True)

In [17]:
all_data

,qid,uid,time,invite_day,u_yesterday_invite,q_yesterday_invite
0,Q2166419046,M401693808,D3865-H22,3865,NaN,15.0
1,Q1550017551,M3392373099,D3844-H11,3844,NaN,1.0
2,Q604029601,M2317670257,D3862-H15,3862,NaN,NaN
3,Q2350061229,M1618461867,D3849-H11,3849,NaN,1.0
4,Q2443223942,M3544409350,D3867-H4,3867,2.0,3.0
5,Q640765464,M2818659842,D3841-H16,3841,NaN,NaN
6,Q795459266,M2818659842,D3861-H20,3861,1.0,NaN
7,Q190554387,M1581217469,D3850-H8,3850,1.0,NaN
8,Q1958712851,M3021021791,D3850-H19,3850,NaN,26.0
9,Q311993584,M1766315480,D3839-H15,3839,NaN,9.0
10,Q110462128,M848334644,D3862-H8,3862,2.0,NaN
11,Q4265255633,M848334644,D3867-H16,3867,NaN,NaN
12,Q885275494,M848334644,D3852-H8,3852,2.0,NaN
13,Q3667003932,M848334644,D3843-H18,3843,1.0,NaN
14,Q3203261036,M848334644,D3863-H14,3863,4.0,NaN
15,Q1392973250,M1008436301,D3847-H19,3847,NaN,6.0
16,Q3785192737,M234356600,D3856-H9,3856,1.0,NaN
17,Q2743747344,M234356600,D3852-H14,3852,1.0,2.0
18,Q1795395339,M4063530679,D3849-H13,3849,NaN,NaN
19,Q233889623,M4063530679,D3846-H22,3846,NaN,9.0
20,Q792624945,M3867096171,D3854-H11,3854,NaN,NaN
21,Q3097516518,M3808996188,D3842-H13,3842,3.0,NaN
22,Q3585956324,M3808996188,D3846-H8,3846,3.0,NaN
23,Q1993990469,M3808996188,D3850-H9,3850,2.0,NaN
24,Q3226256008,M3808996188,D3854-H12,3854,1.0,NaN
25,Q2525843774,M3808996188,D3861-H10,3861,2.0,NaN
26,Q4163388497,M3808996188,D3839-H8,3839,2.0,NaN
27,Q4062946420,M3755026046,D3864-H0,3864,NaN,57.0
28,Q2903515283,M71774990,D3850-H17,3850,NaN,3.0
29,Q1083988747,M3171850588,D3842-H23,3842,1.0,2.0
...,...,...,...,...,...,...
11769443,Q3829602327,M3055556360,D3871-H16,3871,1.0,NaN
11769444,Q978121509,M2341576623,D3871-H8,3871,NaN,1.0
11769445,Q3799316241,M3686321982,D3868-H7,3868,1.0,2.0
11769446,Q586224890,M1757691280,D3871-H15,3871,NaN,6.0
11769447,Q1156535365,M2031642368,D3869-H0,3869,NaN,NaN
11769448,Q1086754099,M2750184738,D3871-H10,3871,NaN,7.0
11769449,Q238531135,M742300351,D3869-H9,3869,NaN,NaN
11769450,Q2712514748,M3565533295,D3873-H18,3873,NaN,NaN
11769451,Q2867766620,M1864017048,D3873-H7,3873,2.0,42.0
11769452,Q679243052,M3915955191,D3868-H3,3868,NaN,NaN
11769453,Q816688891,M2884250892,D3871-H8,3871,NaN,NaN
11769454,Q729775785,M212515408,D3872-H18,3872,2.0,NaN
11769455,Q2750642401,M3885561216,D3872-H15,3872,NaN,NaN
11769456,Q2702020750,M149279583,D3873-H21,3873,NaN,1.0
11769457,Q4131424015,M2861382280,D3868-H14,3868,1.0,NaN
11769458,Q3392634032,M3569667884,D3870-H14,3870,NaN,3.0
11769459,Q4274060389,M3060101660,D3869-H8,3869,NaN,43.0
11769460,Q3847308625,M3370797461,D3870-H22,3870,1.0,NaN
11769461,Q2013872163,M3141952574,D3870-H16,3870,NaN,3.0
11769462,Q3876148676,M1028797787,D3869-H8,3869,NaN,NaN
11769463,Q2516377406,M3018898375,D3868-H9,3868,2.0,NaN
11769464,Q10247829,M693860951,D3873-H9,3873,NaN,NaN
11769465,Q603124625,M2654175916,D3868-H9,3868,NaN,5.0
11769466,Q2324697391,M1912087313,D3873-H12,3873,NaN,NaN
11769467,Q3602223917,M1804122271,D3872-H7,3872,1.0,3.0
11769468,Q1238703523,M2010778235,D3869-H20,3869,NaN,NaN
11769469,Q1074024036,M3131383616,D3872-H21,3872,NaN,NaN
11769470,Q3478846332,M1872860897,D3871-H15,3871,NaN,4.0
11769471,Q734170704,M3574631517,D3871-H8,3871,1.0,NaN
11769472,Q2590286630,M3168697168,D3873-H9,3873,NaN,NaN

In [18]:
all_data[['qid','uid','u_yesterday_invite','q_yesterday_invite']].to_hdf('feature_yesterday_invite2.h5', key='data')