In [1]:
import pandas as pd
import time
import numpy as np

In [2]:
train=pd.read_csv('invite_info.txt',sep='\s+',names=['qid','uid','time','target'])
test=pd.read_csv('invite_info_evaluate_1.txt',sep='\s+',names=['qid','uid','time'])
test2=pd.read_csv('invite_info_evaluate_2_0926.txt',sep='\s+',names=['qid','uid','time'])
all_data=pd.concat([train[['qid','uid','time']],test2,test])

In [3]:
from tqdm import tqdm
tqdm.pandas()

In [4]:
all_data['day']=all_data['time'].progress_apply(lambda x:x[1:].split('-H')[0])

100%|██████████| 11772563/11772563 [00:20<00:00, 585441.62it/s]

In [5]:
def caul_time(x):
    time=x[1:].split('-H')
    return int(time[0])*24+int(time[1])

In [6]:
all_data['time']=all_data['time'].progress_apply(lambda x:caul_time(x))

100%|██████████| 11772563/11772563 [00:28<00:00, 406920.77it/s]

In [7]:
def time_diff_stat(ser):  #code from 陈雄君 陈垂泽 雅典娜杯
    ts = ser.values
    ts_diff = np.diff(ts)
    if ts_diff.shape[0] < 2:
        return 0, 0, 0, 0
    else:
        return ts_diff.min(), ts_diff.max(), ts_diff.mean(), ts_diff.std()

In [8]:
all_data.sort_values(by=['time'], inplace=True)

In [9]:
feature = all_data.groupby(['uid'])['time'].progress_apply(time_diff_stat).reset_index()

100%|██████████| 1451889/1451889 [03:12<00:00, 7533.30it/s]

In [10]:
feature=pd.concat([feature,pd.DataFrame(feature['time'].tolist())],axis=1)

In [11]:
feature.drop(['time'],axis=1,inplace=True)
feature.columns=['uid','intime_gap_min','intime_gap_max','intime_gap_mean','intime_gap_std']

In [12]:
feature=feature.reset_index(drop=True)

In [13]:
feature.to_hdf('feature_intime_gap2.h5', key='data')

In [14]:
featureq = all_data.groupby(['qid'])['time'].progress_apply(time_diff_stat).reset_index()

100%|██████████| 1108278/1108278 [02:25<00:00, 7592.48it/s]

In [15]:
featureq=pd.concat([featureq,pd.DataFrame(featureq['time'].tolist())],axis=1)

In [16]:
featureq.drop(['time'],axis=1,inplace=True)
featureq.columns=['qid','qintime_gap_min','qintime_gap_max','qintime_gap_mean','qintime_gap_std']

In [17]:
featureq=featureq.reset_index(drop=True)

In [18]:
featureq.to_hdf('feature_qintime_gap2.h5', key='data')

In [7]:
##############################################

In [19]:
featureq

,qid,qintime_gap_min,qintime_gap_max,qintime_gap_mean,qintime_gap_std
0,Q1000002524,0,0,0.000000,0.000000
1,Q1000006560,0,0,0.000000,0.000000
2,Q1000007604,0,28,16.714286,9.808368
3,Q1000008276,0,110,24.666667,39.520740
4,Q1000010200,0,0,0.000000,0.000000
5,Q1000020925,0,0,0.000000,0.000000
6,Q1000025766,0,0,0.000000,0.000000
7,Q100002777,0,63,5.666667,17.322112
8,Q100003566,0,6,0.750000,1.984313
9,Q1000036156,0,0,0.000000,0.000000
10,Q1000037824,0,3,1.000000,1.414214
11,Q1000041691,0,0,0.000000,0.000000
12,Q1000049860,14,28,21.000000,7.000000
13,Q1000050745,0,25,3.500000,8.015610
14,Q100005202,0,8,0.228571,1.332789
15,Q1000055583,0,24,12.000000,12.000000
16,Q1000060407,0,0,0.000000,0.000000
17,Q1000070819,1,29,11.333333,12.552114
18,Q1000077463,0,49,8.736842,13.466692
19,Q1000079202,0,76,17.750000,20.718565
20,Q1000084722,0,0,0.000000,0.000000
21,Q1000086802,0,0,0.000000,0.000000
22,Q1000087420,0,0,0.000000,0.000000
23,Q1000088167,0,0,0.000000,0.000000
24,Q1000092002,0,178,16.868421,32.560204
25,Q1000102961,0,0,0.000000,0.000000
26,Q1000103600,0,0,0.000000,0.000000
27,Q1000103719,0,24,12.000000,12.000000
28,Q1000109519,0,0,0.000000,0.000000
29,Q100010975,0,0,0.000000,0.000000
...,...,...,...,...,...
1108248,Q999906478,0,20,5.333333,7.180220
1108249,Q999925104,0,0,0.000000,0.000000
1108250,Q999925217,0,49,3.653846,10.257989
1108251,Q999928848,0,262,24.480000,59.089843
1108252,Q99993697,0,23,1.238095,4.907766
1108253,Q999941279,0,310,47.857143,107.366433
1108254,Q999941734,0,173,24.714286,60.537389
1108255,Q99994205,0,14,2.857143,4.997959
1108256,Q999944094,0,76,25.333333,35.826744
1108257,Q99995466,0,0,0.000000,0.000000
1108258,Q999958198,0,19,6.333333,8.956686
1108259,Q999962730,0,0,0.000000,0.000000
1108260,Q999967056,0,0,0.000000,0.000000
1108261,Q99996827,0,0,0.000000,0.000000
1108262,Q999969820,0,27,13.500000,13.500000
1108263,Q999970938,0,23,8.666667,10.208929
1108264,Q999972709,10,109,59.500000,49.500000
1108265,Q999974398,0,0,0.000000,0.000000
1108266,Q999976398,0,82,20.571429,29.908705
1108267,Q999977222,0,0,0.000000,0.000000
1108268,Q999977345,0,0,0.000000,0.000000
1108269,Q999978668,0,0,0.000000,0.000000
1108270,Q999986135,0,32,15.333333,13.097922
1108271,Q999990752,0,47,5.875000,15.543789
1108272,Q999992666,0,14,2.800000,5.600000
1108273,Q999993281,0,62,8.100000,16.074514
1108274,Q999995156,0,202,15.333333,50.372832
1108275,Q999996608,0,47,7.533333,15.666809
1108276,Q999997494,0,8,1.333333,2.981424
1108277,Q999999307,0,48,8.545455,14.822364